spring.application.name=stock-day-trading-simulator

tradingsim.finnhub.base-url=https://finnhub.io/api/v1
tradingsim.finnhub.api-key=${FINNHUB_API_KEY:}
tradingsim.quote-cache-duration=PT10S
tradingsim.starting-cash=100000.00

server.error.include-message=never
