spring.application.name=replaylab-trading-simulator

tradingsim.finnhub.base-url=https://finnhub.io/api/v1
tradingsim.finnhub.api-key=${FINNHUB_API_KEY:}
tradingsim.quote-cache-duration=PT10S
tradingsim.starting-cash=100000.00

server.error.include-message=never
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
