CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE paper_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id),
    starting_cash NUMERIC(19, 2) NOT NULL,
    cash NUMERIC(19, 2) NOT NULL,
    realized_profit_loss NUMERIC(19, 2) NOT NULL
);

CREATE TABLE paper_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES paper_accounts(id),
    symbol VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL,
    average_price NUMERIC(19, 6) NOT NULL,
    realized_profit_loss NUMERIC(19, 2) NOT NULL,
    CONSTRAINT uk_position_account_symbol UNIQUE (account_id, symbol)
);

CREATE TABLE paper_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES app_users(id),
    symbol VARCHAR(20) NOT NULL,
    side VARCHAR(8) NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC(19, 6) NOT NULL,
    total NUMERIC(19, 2) NOT NULL,
    executed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE saved_backtests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES app_users(id),
    symbol VARCHAR(20) NOT NULL,
    strategy VARCHAR(40) NOT NULL,
    result_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES app_users(id),
    title VARCHAR(120) NOT NULL,
    notes VARCHAR(5000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_paper_trades_owner_time
    ON paper_trades(owner_id, executed_at DESC);
CREATE INDEX idx_saved_backtests_owner_time
    ON saved_backtests(owner_id, created_at DESC);
CREATE INDEX idx_journal_entries_owner_time
    ON journal_entries(owner_id, created_at DESC);
